version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    image: app:medium-backend
    container_name: django-container
    command: python manage.py runserver 0.0.0.0:8000
