# Generated by Django 4.1 on 2022-09-14 15:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import user_accounts.models
import user_accounts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='your full name', max_length=100)),
                ('cnic', models.CharField(blank=True, help_text='your CNIC in the following format: xxxxx-xxxxxxx-x', max_length=15, validators=[django.core.validators.RegexValidator('\\d{5}\\-\\d{7}\\-\\d{1}', 'CNIC format needs to be - XXXXX-XXXXXXX-X')])),
                ('contact_number', models.CharField(blank=True, help_text='your contact number in the format: +xxxxxxxxxxx', max_length=13, validators=[django.core.validators.RegexValidator('^\\+\\d{12}$', 'Phone number format needs to be +XXXXXXXXXXXX')])),
                ('address', models.TextField(blank=True, help_text='your address')),
                ('country', django_countries.fields.CountryField(blank=True, default='PK', help_text='your country', max_length=2)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('N/A', 'Do not specify')], default='', max_length=6)),
                ('bio', models.TextField(blank=True, help_text='your bio')),
                ('profile_pic', models.ImageField(blank=True, default='images/default/default_user.png', upload_to=user_accounts.models.Profile.name_file, validators=[user_accounts.validators.validate_file_extension])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
